services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./apache.conf:/etc/apache2/conf-available/apache.conf
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=teamdata
      - MYSQL_USER=star
      - MYSQL_PASSWORD=pass
      - TZ=Asia/Tokyo

    volumes:
      - db:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/my.cnf

    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpadmin:
    image: phpmyadmin
    ports:
      - 8085:80
    environment:
      - PMA_HOST=db

volumes:
  db:
